'use client';

import React, { createContext, useContext, useState } from 'react';

type Language = 'th' | 'en' | 'cn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Initialize from localStorage on client-side
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'th' || savedLanguage === 'en' || savedLanguage === 'cn')) {
        return savedLanguage;
      }
    }
    return 'th'; // Default to Thai
  });

  // Save language to localStorage when changed
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    const translation = translations[language]?.[key];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// Translations object
const translations: Record<Language, Record<string, string>> = {
  th: {
    // Language
    'lang.code': 'th',

    // Navigation
    'nav.home': 'หน้าแรก',
    'nav.employees': 'พนักงาน',
    'nav.attendance': 'เวลาเข้างาน',
    'nav.leave': 'การลางาน',
    'nav.payroll': 'เงินเดือน',
    'nav.ai': 'AI Features',
    'nav.reports': 'รายงาน',
    'nav.auto': 'AUTO',

    // Dashboard/Home
    'home.title': 'ระบบคำนวณเงินเดือน',
    'home.subtitle': 'ภาพรวมข้อมูลเงินเดือนพนักงาน',
    'home.selectPeriod': 'เลือกรอบเงินเดือนเพื่อดูข้อมูล',
    'home.selectPeriodDesc': 'กรุณาเลือกรอบเงินเดือนจากด้านบนเพื่อแสดงข้อมูลสรุป',

    // Payroll Table
    'payroll.title': 'รายการเงินเดือนพนักงาน',
    'payroll.period': 'รอบ',
    'payroll.employees': 'พนักงาน',
    'payroll.people': 'คน',
    'payroll.viewDetails': 'ดูรายละเอียดเต็ม',
    'payroll.search': 'ค้นหาพนักงาน...',
    'payroll.loading': 'กำลังโหลดข้อมูล...',
    'payroll.noData': 'ยังไม่มีข้อมูล',
    'payroll.noResults': 'ไม่พบข้อมูลที่ค้นหา',
    'payroll.empId': 'รหัส',
    'payroll.name': 'ชื่อ-นามสกุล',
    'payroll.department': 'แผนก',
    'payroll.day': 'วันที่',
    'payroll.totalOT': 'OT รวม',
    'payroll.otHours': 'OT (ชม.)',
    'payroll.otAmount': 'ค่า OT',
    'payroll.gross': 'Gross',
    'payroll.net': 'Net',

    // Leave Records
    'leave.title': 'ประวัติการลาทั้งหมด',
    'leave.subtitle': 'รายการการลางานของพนักงานทั้งหมด',
    'leave.manage': 'จัดการการลา',
    'leave.selectDateRange': 'เลือกช่วงเวลา',
    'leave.showing': 'แสดง',
    'leave.items': 'รายการ',
    'leave.outOf': 'จากทั้งหมด',
    'leave.date': 'วันที่ลา',
    'leave.empId': 'รหัสพนักงาน',
    'leave.empName': 'ชื่อ-นามสกุล',
    'leave.department': 'แผนก',
    'leave.type': 'ประเภท',
    'leave.reason': 'เหตุผล',
    'leave.noLeaves': 'ไม่มีรายการลา',
    'leave.noLeavesInRange': 'ไม่พบรายการลาในช่วงเวลาที่เลือก',
    'leave.typeSick': 'ลาป่วย',
    'leave.typePersonal': 'ลากิจ',
    'leave.typeVacation': 'ลาพักร้อน',

    // Financial Summary
    'finance.baseSalary': 'เงินเดือนฐาน (ทั้งหมด)',
    'finance.baseSalaryDesc': 'ไม่รวมค่า OT',
    'finance.otTotal': 'ค่า OT (ทั้งหมด)',
    'finance.otTotalDesc': 'ค่าล่วงเวลาทั้งหมด',
    'finance.grossTotal': 'รวม (ก่อนหัก)',
    'finance.grossSalary': 'Gross Salary',
    'finance.netTotal': 'รวม (สุทธิ)',
    'finance.netDesc': 'หลังหักภาษี + ประกันสังคม',

    // Statistics
    'stats.topOT': 'Top 5 OT สูงสุด',
    'stats.lowOT': 'Top 5 OT ต่ำสุด',
    'stats.deptAvgOT': 'OT เฉลี่ยแต่ละแผนก',
    'stats.topLeave': 'ลางานมากที่สุด 5 อันดับ',
    'stats.lowLeave': 'ลางานน้อยที่สุด 5 อันดับ',
    'stats.hours': 'ชม.',
    'stats.days': 'วัน',

    // Date Range Picker
    'dateRange.select': 'เลือกช่วงเวลา',
    'dateRange.startDate': 'วันที่เริ่มต้น',
    'dateRange.endDate': 'วันที่สิ้นสุด',
    'dateRange.clear': 'ล้าง',
    'dateRange.ok': 'ตกลง',

    // Leave Page
    'leavePage.title': 'จัดการการลางาน',
    'leavePage.subtitle': 'บันทึกและจัดการวันลาของพนักงาน',
    'leavePage.addLeave': 'บันทึกการลา',
    'leavePage.selectEmployee': 'เลือกพนักงานและวันที่ลา',
    'leavePage.searchEmployee': 'ค้นหาพนักงาน',
    'leavePage.searchPlaceholder': 'พิมพ์ชื่อหรือรหัสพนักงาน...',
    'leavePage.leaveDate': 'วันที่ลา',
    'leavePage.leaveType': 'ประเภทการลา',
    'leavePage.reasonOptional': 'เหตุผล (ไม่บังคับ)',
    'leavePage.reasonPlaceholder': 'ระบุเหตุผลการลา...',
    'leavePage.submit': 'บันทึกการลา',
    'leavePage.recentLeaves': 'รายการลางาน',
    'leavePage.recent10': 'ล่าสุด 10 รายการ',
    'leavePage.allLeaves': 'ประวัติการลาทั้งหมด',
    'leavePage.selectEmployeeError': 'กรุณาเลือกพนักงานและวันที่ลา',
    'leavePage.saveError': 'ไม่สามารถบันทึกการลาได้',
    'leavePage.saveSuccess': 'บันทึกการลาสำเร็จ',
    'leavePage.deleteConfirm': 'ต้องการลบรายการลานี้?',
    'leavePage.deleteError': 'ไม่สามารถลบรายการลาได้',
    'leavePage.deleteSuccess': 'ลบรายการลาสำเร็จ',
    'leavePage.noLeaveItems': 'ยังไม่มีรายการลา',
    'leavePage.showingItems': 'แสดง {count} รายการ',
    'leavePage.outOfTotal': '(จากทั้งหมด {total} รายการ)',
    'leavePage.typeOther': 'อื่นๆ',

    // Employees Page
    'employees.title': 'จัดการพนักงาน',
    'employees.subtitle': 'รายชื่อพนักงานทั้งหมดในระบบ',
    'employees.importCSV': 'นำเข้า CSV',
    'employees.list': 'รายชื่อพนักงาน',
    'employees.totalCount': 'ทั้งหมด {count} คน',
    'employees.searchPlaceholder': 'ค้นหาพนักงาน...',
    'employees.employeeId': 'รหัสพนักงาน',
    'employees.name': 'ชื่อ-นามสกุล',
    'employees.department': 'แผนก',
    'employees.baseSalary': 'เงินเดือนฐาน',
    'employees.otRate': 'อัตรา OT/ชม.',
    'employees.loading': 'กำลังโหลด...',
    'employees.noData': 'ไม่พบข้อมูลพนักงาน',
    'employees.loadError': 'ไม่สามารถโหลดข้อมูลพนักงานได้',
    'employees.importSuccess': 'นำเข้าพนักงาน {count} คน สำเร็จ',
    'employees.importError': 'เกิดข้อผิดพลาดในการนำเข้าข้อมูล',

    // Attendance Page
    'attendance.title': 'บันทึกเวลาทำงาน',
    'attendance.subtitle': 'นำเข้าข้อมูลการแสกนเข้า-ออกงานจากเครื่องสแกนใบหน้า',
    'attendance.import': 'นำเข้าข้อมูล',
    'attendance.uploadDesc': 'อัปโหลดไฟล์ .txt หรือวางข้อมูลด้านล่าง',
    'attendance.uploadFile': 'อัปโหลดไฟล์',
    'attendance.pasteHere': 'หรือวางข้อมูลที่นี่',
    'attendance.importing': 'กำลังนำเข้า...',
    'attendance.importData': 'นำเข้าข้อมูล',
    'attendance.dataFormat': 'รูปแบบข้อมูล',
    'attendance.formatDesc': 'ข้อมูลที่ได้จากเครื่องสแกนต้องมีรูปแบบดังนี้',
    'attendance.formatExplain': 'คำอธิบายรูปแบบ:',
    'attendance.formatMachineId': 'รหัสเครื่อง (01, 04, etc.)',
    'attendance.formatDate': 'วันที่ (DD-MM-YYYY)',
    'attendance.formatTime': 'เวลา (HH:MM:SS)',
    'attendance.formatEmpId': 'รหัสพนักงาน (\'20055675)',
    'attendance.formatType': 'ประเภท (1 = เข้า, 2 = ออก)',
    'attendance.importSuccess': 'นำเข้าสำเร็จ!',
    'attendance.scansImported': 'นำเข้า {count} การแสกน',
    'attendance.recordsCreated': 'สร้าง {count} รายการเวลาทำงาน',
    'attendance.scansSkipped': 'ข้าม {count} รายการ (ไม่มีรหัสพนักงานในระบบ)',
    'attendance.fileReadSuccess': 'อ่านไฟล์สำเร็จ',
    'attendance.enterDataError': 'กรุณาใส่ข้อมูลการแสกน',

    // Reports Page
    'reports.title': 'รายงาน',
    'reports.subtitle': 'ส่งออกและดูรายงานต่างๆ ในระบบ',
    'reports.attendance': 'รายงานเวลาทำงาน',
    'reports.attendanceDesc': 'รายงานการเข้า-ออกงานของพนักงาน',
    'reports.exportExcel': 'ส่งออก Excel',
    'reports.otMonthly': 'รายงาน OT รายเดือน',
    'reports.otMonthlyDesc': 'สรุปชั่วโมง OT ของพนักงานแต่ละคน',
    'reports.payroll': 'รายงานเงินเดือน',
    'reports.payrollDesc': 'รายงานเงินเดือนพนักงานรายเดือน',
    'reports.exportPDF': 'ส่งออก PDF',
    'reports.payslip': 'สลิปเงินเดือน',
    'reports.payslipDesc': 'ออกสลิปเงินเดือนสำหรับพนักงาน',
    'reports.createPayslip': 'สร้างสลิป PDF',
    'reports.leave': 'รายงานการลา',
    'reports.leaveDesc': 'สรุปการลางานของพนักงาน',
    'reports.yearlyReport': 'รายงานสรุปประจำปี',
    'reports.yearlyReportDesc': 'สรุปเงินเดือนและ OT ตลอดทั้งปี',
    'reports.viewReport': 'ดูรายงาน',
    'reports.tips': 'คำแนะนำ',
    'reports.tip1': 'รายงานทั้งหมดสามารถส่งออกเป็นไฟล์ Excel หรือ PDF ได้',
    'reports.tip2': 'สลิปเงินเดือนสามารถออกเป็น PDF สำหรับส่งให้พนักงานได้',
    'reports.tip3': 'รายงานสามารถกรองตามช่วงเวลาและแผนกได้',

    // AI Features Page
    'ai.subtitle': 'ใช้ AI เพื่อวิเคราะห์ข้อมูล ตอบคำถาม และช่วยเหลือในการใช้งานระบบ Payroll แบบอัตโนมัติ',
    'ai.capabilities': 'คุณสมบัติ AI',
    'ai.cap1': 'ตอบคำถามเกี่ยวกับข้อมูลพนักงานและเงินเดือน',
    'ai.cap2': 'วิเคราะห์ข้อมูล OT และประสิทธิภาพการทำงาน',
    'ai.cap3': 'แนะนำวิธีการใช้งานระบบ',
    'ai.cap4': 'สร้างรายงานและสรุปข้อมูลอัตโนมัติ',
    'ai.examples': 'ตัวอย่างคำถาม',
    'ai.example1': 'พนักงานคนไหนทำ OT มากที่สุด 5 อันดับแรก?',
    'ai.example2': 'ค่าใช้จ่ายเงินเดือนรวมของแผนก Production เท่าไหร่?',
    'ai.example3': 'วิธีการ import ข้อมูลเวลาเข้างานทำอย่างไร?',
    'ai.example4': 'อธิบายการคำนวณ OT ในระบบหน่อย',
    'ai.tips': 'เคล็ดลับ',
    'ai.tip1': 'ถามคำถามแบบเฉพาะเจาะจงเพื่อผลลัพธ์ที่ดีขึ้น',
    'ai.tip2': 'สามารถถามต่อเนื่องในบริบทเดียวกันได้',
    'ai.tip3': 'AI จะจำบริบทการสนทนาก่อนหน้า',
    'ai.comingSoon': 'เร็วๆ นี้',

    // Payroll Page (Additional Keys)
    'payroll.pageTitle': 'จัดการเงินเดือนพนักงาน',
    'payroll.pageSubtitle': 'คำนวณและจัดการข้อมูลเงินเดือนพนักงาน',
    'payroll.startDate': 'วันที่เริ่มต้น',
    'payroll.endDate': 'วันที่สิ้นสุด',
    'payroll.autoCalculated': 'คำนวณอัตโนมัติ',
    'payroll.startDateHint': 'เลือกวันที่ 11 หรือ 26 เท่านั้น',
    'payroll.endDateHint': 'คำนวณจากวันเริ่มต้น +14 วัน',
    'payroll.baseSalaryCard': 'เงินเดือนฐาน',
    'payroll.excludingOT': 'ไม่รวมค่า OT',
    'payroll.otTotalCard': 'ค่า OT รวม',
    'payroll.totalOTDesc': 'ค่าล่วงเวลาทั้งหมด',
    'payroll.grossCard': 'รวม (ก่อนหัก)',
    'payroll.netCard': 'รวม (สุทธิ)',
    'payroll.netDesc': 'หลังหักภาษี + ประกัน',
    'payroll.employeeList': 'รายการเงินเดือนพนักงาน',
    'payroll.totalEmployees': 'พนักงานทั้งหมด {count} คน',
    'payroll.searchResults': 'ผลการค้นหา {count} คน',
    'payroll.searchByName': 'ค้นหาด้วยชื่อหรือรหัสพนักงาน...',
    'payroll.exportExcel': 'ส่งออก Excel',
    'payroll.calculateHint': 'กดปุ่ม "คำนวณ" เพื่อคำนวณเงินเดือนของรอบนี้',
    'payroll.createPeriod': 'สร้างรอบเงินเดือน',
    'payroll.periodSettings': 'กำหนดรอบการจ่ายเงินเดือนใหม่',
    'payroll.periodName': 'ชื่อรอบ',
    'payroll.periodExample': 'เช่น ตุลาคม 2025',
    'payroll.paymentDate': 'วันจ่ายเงิน',
    'payroll.createPeriodBtn': 'สร้างรอบเงินเดือน',
    'payroll.allPeriods': 'รอบเงินเดือนทั้งหมด',
    'payroll.selectPeriodDesc': 'เลือกรอบเพื่อคำนวณหรือดูรายละเอียดเงินเดือน',
    'payroll.periodRange': 'ระยะเวลา:',
    'payroll.paymentOn': 'จ่ายวันที่:',
    'payroll.statusPaid': 'จ่ายแล้ว',
    'payroll.statusApproved': 'อนุมัติแล้ว',
    'payroll.statusDraft': 'ร่าง',
    'payroll.calculate': 'คำนวณ',
    'payroll.viewData': 'ดูข้อมูล',
    'payroll.noPeriods': 'ยังไม่มีรอบเงินเดือน',
    'payroll.createFirstPeriod': 'สร้างรอบเงินเดือนใหม่เพื่อเริ่มต้น',
    'payroll.loadingData': 'กำลังโหลด...',
    'payroll.startDateError': 'วันเริ่มต้นต้องเป็นวันที่ 11 หรือ 26 เท่านั้น',
    'payroll.selectStartDateError': 'กรุณาเลือกวันเริ่มต้นที่ถูกต้อง',
    'payroll.createError': 'ไม่สามารถสร้างรอบเงินเดือนได้',
    'payroll.createSuccess': 'สร้างรอบเงินเดือนสำเร็จ',
    'payroll.calculateError': 'ไม่สามารถคำนวณเงินเดือนได้',
    'payroll.calculateSuccess': 'คำนวณเงินเดือนสำเร็จ {count} รายการ',
  },
  en: {
    // Language
    'lang.code': 'en',

    // Navigation
    'nav.home': 'Home',
    'nav.employees': 'Employees',
    'nav.attendance': 'Attendance',
    'nav.leave': 'Leave',
    'nav.payroll': 'Payroll',
    'nav.ai': 'AI Features',
    'nav.reports': 'Reports',
    'nav.auto': 'AUTO',

    // Dashboard/Home
    'home.title': 'Payroll System',
    'home.subtitle': 'Employee payroll overview',
    'home.selectPeriod': 'Select payroll period to view data',
    'home.selectPeriodDesc': 'Please select a payroll period from above to display summary',

    // Payroll Table
    'payroll.title': 'Employee Payroll List',
    'payroll.period': 'Period',
    'payroll.employees': 'Employees',
    'payroll.people': 'people',
    'payroll.viewDetails': 'View Details',
    'payroll.search': 'Search employee...',
    'payroll.loading': 'Loading data...',
    'payroll.noData': 'No data available',
    'payroll.noResults': 'No results found',
    'payroll.empId': 'ID',
    'payroll.name': 'Name',
    'payroll.department': 'Department',
    'payroll.day': 'Day',
    'payroll.totalOT': 'Total OT',
    'payroll.otHours': 'OT (hrs)',
    'payroll.otAmount': 'OT Amount',
    'payroll.gross': 'Gross',
    'payroll.net': 'Net',

    // Leave Records
    'leave.title': 'All Leave Records',
    'leave.subtitle': 'All employee leave records',
    'leave.manage': 'Manage Leave',
    'leave.selectDateRange': 'Select date range',
    'leave.showing': 'Showing',
    'leave.items': 'items',
    'leave.outOf': 'out of',
    'leave.date': 'Leave Date',
    'leave.empId': 'Employee ID',
    'leave.empName': 'Name',
    'leave.department': 'Department',
    'leave.type': 'Type',
    'leave.reason': 'Reason',
    'leave.noLeaves': 'No leave records',
    'leave.noLeavesInRange': 'No leave records in selected date range',
    'leave.typeSick': 'Sick',
    'leave.typePersonal': 'Personal',
    'leave.typeVacation': 'Vacation',

    // Financial Summary
    'finance.baseSalary': 'Base Salary (Total)',
    'finance.baseSalaryDesc': 'Excluding OT',
    'finance.otTotal': 'OT Amount (Total)',
    'finance.otTotalDesc': 'Total overtime pay',
    'finance.grossTotal': 'Total (Before Deduction)',
    'finance.grossSalary': 'Gross Salary',
    'finance.netTotal': 'Total (Net)',
    'finance.netDesc': 'After tax + social security',

    // Statistics
    'stats.topOT': 'Top 5 Highest OT',
    'stats.lowOT': 'Top 5 Lowest OT',
    'stats.deptAvgOT': 'Average OT by Department',
    'stats.topLeave': 'Top 5 Most Leave',
    'stats.lowLeave': 'Top 5 Least Leave',
    'stats.hours': 'hrs',
    'stats.days': 'days',

    // Date Range Picker
    'dateRange.select': 'Select date range',
    'dateRange.startDate': 'Start Date',
    'dateRange.endDate': 'End Date',
    'dateRange.clear': 'Clear',
    'dateRange.ok': 'OK',

    // Leave Page
    'leavePage.title': 'Leave Management',
    'leavePage.subtitle': 'Record and manage employee leave',
    'leavePage.addLeave': 'Record Leave',
    'leavePage.selectEmployee': 'Select employee and leave date',
    'leavePage.searchEmployee': 'Search Employee',
    'leavePage.searchPlaceholder': 'Type name or employee ID...',
    'leavePage.leaveDate': 'Leave Date',
    'leavePage.leaveType': 'Leave Type',
    'leavePage.reasonOptional': 'Reason (Optional)',
    'leavePage.reasonPlaceholder': 'Enter leave reason...',
    'leavePage.submit': 'Submit Leave',
    'leavePage.recentLeaves': 'Leave Records',
    'leavePage.recent10': 'Recent 10 records',
    'leavePage.allLeaves': 'All Leave Records',
    'leavePage.selectEmployeeError': 'Please select employee and leave date',
    'leavePage.saveError': 'Failed to save leave record',
    'leavePage.saveSuccess': 'Leave record saved successfully',
    'leavePage.deleteConfirm': 'Do you want to delete this leave record?',
    'leavePage.deleteError': 'Failed to delete leave record',
    'leavePage.deleteSuccess': 'Leave record deleted successfully',
    'leavePage.noLeaveItems': 'No leave records yet',
    'leavePage.showingItems': 'Showing {count} items',
    'leavePage.outOfTotal': '(out of {total} total)',
    'leavePage.typeOther': 'Other',

    // Employees Page
    'employees.title': 'Employee Management',
    'employees.subtitle': 'All employees in the system',
    'employees.importCSV': 'Import CSV',
    'employees.list': 'Employee List',
    'employees.totalCount': 'Total {count} people',
    'employees.searchPlaceholder': 'Search employees...',
    'employees.employeeId': 'Employee ID',
    'employees.name': 'Name',
    'employees.department': 'Department',
    'employees.baseSalary': 'Base Salary',
    'employees.otRate': 'OT Rate/hr',
    'employees.loading': 'Loading...',
    'employees.noData': 'No employees found',
    'employees.loadError': 'Failed to load employee data',
    'employees.importSuccess': 'Successfully imported {count} employees',
    'employees.importError': 'Error importing data',

    // Attendance Page
    'attendance.title': 'Record Work Time',
    'attendance.subtitle': 'Import attendance scan data from facial recognition device',
    'attendance.import': 'Import Data',
    'attendance.uploadDesc': 'Upload .txt file or paste data below',
    'attendance.uploadFile': 'Upload File',
    'attendance.pasteHere': 'Or paste data here',
    'attendance.importing': 'Importing...',
    'attendance.importData': 'Import Data',
    'attendance.dataFormat': 'Data Format',
    'attendance.formatDesc': 'Scan data must follow this format',
    'attendance.formatExplain': 'Format explanation:',
    'attendance.formatMachineId': 'Machine ID (01, 04, etc.)',
    'attendance.formatDate': 'Date (DD-MM-YYYY)',
    'attendance.formatTime': 'Time (HH:MM:SS)',
    'attendance.formatEmpId': 'Employee ID (\'20055675)',
    'attendance.formatType': 'Type (1 = In, 2 = Out)',
    'attendance.importSuccess': 'Import successful!',
    'attendance.scansImported': 'Imported {count} scans',
    'attendance.recordsCreated': 'Created {count} work records',
    'attendance.scansSkipped': 'Skipped {count} records (employee not in system)',
    'attendance.fileReadSuccess': 'File read successfully',
    'attendance.enterDataError': 'Please enter scan data',

    // Reports Page
    'reports.title': 'Reports',
    'reports.subtitle': 'Export and view various system reports',
    'reports.attendance': 'Attendance Report',
    'reports.attendanceDesc': 'Employee check-in/check-out report',
    'reports.exportExcel': 'Export Excel',
    'reports.otMonthly': 'Monthly OT Report',
    'reports.otMonthlyDesc': 'Summary of employee overtime hours',
    'reports.payroll': 'Payroll Report',
    'reports.payrollDesc': 'Monthly employee payroll report',
    'reports.exportPDF': 'Export PDF',
    'reports.payslip': 'Payslip',
    'reports.payslipDesc': 'Generate payslips for employees',
    'reports.createPayslip': 'Create Payslip PDF',
    'reports.leave': 'Leave Report',
    'reports.leaveDesc': 'Summary of employee leave',
    'reports.yearlyReport': 'Yearly Summary Report',
    'reports.yearlyReportDesc': 'Summary of salary and OT throughout the year',
    'reports.viewReport': 'View Report',
    'reports.tips': 'Tips',
    'reports.tip1': 'All reports can be exported as Excel or PDF files',
    'reports.tip2': 'Payslips can be generated as PDF for employees',
    'reports.tip3': 'Reports can be filtered by date range and department',

    // AI Features Page
    'ai.subtitle': 'Use AI to analyze data, answer questions, and assist with the Payroll system automatically',
    'ai.capabilities': 'AI Capabilities',
    'ai.cap1': 'Answer questions about employee and payroll data',
    'ai.cap2': 'Analyze OT data and work performance',
    'ai.cap3': 'Provide guidance on system usage',
    'ai.cap4': 'Generate reports and summaries automatically',
    'ai.examples': 'Example Questions',
    'ai.example1': 'Which employees have the highest OT in top 5?',
    'ai.example2': 'What is the total payroll expense for Production department?',
    'ai.example3': 'How do I import attendance data?',
    'ai.example4': 'Explain how OT is calculated in the system',
    'ai.tips': 'Tips',
    'ai.tip1': 'Ask specific questions for better results',
    'ai.tip2': 'You can ask follow-up questions in the same context',
    'ai.tip3': 'AI remembers previous conversation context',
    'ai.comingSoon': 'Coming Soon',

    // Payroll Page (Additional Keys)
    'payroll.pageTitle': 'Payroll Management',
    'payroll.pageSubtitle': 'Calculate and manage employee payroll data',
    'payroll.startDate': 'Start Date',
    'payroll.endDate': 'End Date',
    'payroll.autoCalculated': 'Auto-calculated',
    'payroll.startDateHint': 'Select 11th or 26th only',
    'payroll.endDateHint': 'Calculated from start date +14 days',
    'payroll.baseSalaryCard': 'Base Salary',
    'payroll.excludingOT': 'Excluding OT',
    'payroll.otTotalCard': 'Total OT',
    'payroll.totalOTDesc': 'Total overtime pay',
    'payroll.grossCard': 'Total (Before Deduction)',
    'payroll.netCard': 'Total (Net)',
    'payroll.netDesc': 'After tax + insurance',
    'payroll.employeeList': 'Employee Payroll List',
    'payroll.totalEmployees': 'Total {count} employees',
    'payroll.searchResults': 'Search results {count} people',
    'payroll.searchByName': 'Search by name or employee ID...',
    'payroll.exportExcel': 'Export Excel',
    'payroll.calculateHint': 'Click "Calculate" button to calculate payroll for this period',
    'payroll.createPeriod': 'Create Payroll Period',
    'payroll.periodSettings': 'Set new payroll period',
    'payroll.periodName': 'Period Name',
    'payroll.periodExample': 'e.g. October 2025',
    'payroll.paymentDate': 'Payment Date',
    'payroll.createPeriodBtn': 'Create Payroll Period',
    'payroll.allPeriods': 'All Payroll Periods',
    'payroll.selectPeriodDesc': 'Select period to calculate or view payroll details',
    'payroll.periodRange': 'Period:',
    'payroll.paymentOn': 'Payment on:',
    'payroll.statusPaid': 'Paid',
    'payroll.statusApproved': 'Approved',
    'payroll.statusDraft': 'Draft',
    'payroll.calculate': 'Calculate',
    'payroll.viewData': 'View Data',
    'payroll.noPeriods': 'No payroll periods yet',
    'payroll.createFirstPeriod': 'Create a new payroll period to get started',
    'payroll.loadingData': 'Loading...',
    'payroll.startDateError': 'Start date must be 11th or 26th only',
    'payroll.selectStartDateError': 'Please select a valid start date',
    'payroll.createError': 'Failed to create payroll period',
    'payroll.createSuccess': 'Payroll period created successfully',
    'payroll.calculateError': 'Failed to calculate payroll',
    'payroll.calculateSuccess': 'Successfully calculated {count} payroll records',
  },
  cn: {
    // Language
    'lang.code': 'cn',

    // Navigation
    'nav.home': '首页',
    'nav.employees': '员工',
    'nav.attendance': '考勤',
    'nav.leave': '请假',
    'nav.payroll': '薪资',
    'nav.ai': 'AI功能',
    'nav.reports': '报告',
    'nav.auto': '自动',

    // Dashboard/Home
    'home.title': '薪资管理系统',
    'home.subtitle': '员工薪资概览',
    'home.selectPeriod': '选择薪资周期查看数据',
    'home.selectPeriodDesc': '请从上方选择薪资周期以显示摘要',

    // Payroll Table
    'payroll.title': '员工薪资清单',
    'payroll.period': '周期',
    'payroll.employees': '员工',
    'payroll.people': '人',
    'payroll.viewDetails': '查看详情',
    'payroll.search': '搜索员工...',
    'payroll.loading': '加载数据中...',
    'payroll.noData': '暂无数据',
    'payroll.noResults': '未找到搜索结果',
    'payroll.empId': '工号',
    'payroll.name': '姓名',
    'payroll.department': '部门',
    'payroll.day': '日',
    'payroll.totalOT': '总加班',
    'payroll.otHours': '加班（小时）',
    'payroll.otAmount': '加班费',
    'payroll.gross': '毛薪',
    'payroll.net': '净薪',

    // Leave Records
    'leave.title': '全部请假记录',
    'leave.subtitle': '全部员工请假记录',
    'leave.manage': '管理请假',
    'leave.selectDateRange': '选择日期范围',
    'leave.showing': '显示',
    'leave.items': '项',
    'leave.outOf': '共',
    'leave.date': '请假日期',
    'leave.empId': '员工工号',
    'leave.empName': '姓名',
    'leave.department': '部门',
    'leave.type': '类型',
    'leave.reason': '原因',
    'leave.noLeaves': '无请假记录',
    'leave.noLeavesInRange': '所选日期范围内无请假记录',
    'leave.typeSick': '病假',
    'leave.typePersonal': '事假',
    'leave.typeVacation': '年假',

    // Financial Summary
    'finance.baseSalary': '基本工资（总计）',
    'finance.baseSalaryDesc': '不包括加班费',
    'finance.otTotal': '加班费（总计）',
    'finance.otTotalDesc': '全部加班费',
    'finance.grossTotal': '总计（税前）',
    'finance.grossSalary': '毛薪',
    'finance.netTotal': '总计（净额）',
    'finance.netDesc': '扣税+社保后',

    // Statistics
    'stats.topOT': '加班时长前5',
    'stats.lowOT': '加班时长后5',
    'stats.deptAvgOT': '各部门平均加班',
    'stats.topLeave': '请假最多前5',
    'stats.lowLeave': '请假最少前5',
    'stats.hours': '小时',
    'stats.days': '天',

    // Date Range Picker
    'dateRange.select': '选择日期范围',
    'dateRange.startDate': '开始日期',
    'dateRange.endDate': '结束日期',
    'dateRange.clear': '清除',
    'dateRange.ok': '确定',

    // Leave Page
    'leavePage.title': '请假管理',
    'leavePage.subtitle': '记录和管理员工请假',
    'leavePage.addLeave': '记录请假',
    'leavePage.selectEmployee': '选择员工和请假日期',
    'leavePage.searchEmployee': '搜索员工',
    'leavePage.searchPlaceholder': '输入姓名或工号...',
    'leavePage.leaveDate': '请假日期',
    'leavePage.leaveType': '请假类型',
    'leavePage.reasonOptional': '原因（可选）',
    'leavePage.reasonPlaceholder': '输入请假原因...',
    'leavePage.submit': '提交请假',
    'leavePage.recentLeaves': '请假记录',
    'leavePage.recent10': '最近10条记录',
    'leavePage.allLeaves': '全部请假记录',
    'leavePage.selectEmployeeError': '请选择员工和请假日期',
    'leavePage.saveError': '无法保存请假记录',
    'leavePage.saveSuccess': '请假记录保存成功',
    'leavePage.deleteConfirm': '要删除此请假记录吗？',
    'leavePage.deleteError': '无法删除请假记录',
    'leavePage.deleteSuccess': '请假记录已删除',
    'leavePage.noLeaveItems': '暂无请假记录',
    'leavePage.showingItems': '显示 {count} 项',
    'leavePage.outOfTotal': '（共 {total} 项）',
    'leavePage.typeOther': '其他',

    // Employees Page
    'employees.title': '员工管理',
    'employees.subtitle': '系统中的所有员工',
    'employees.importCSV': '导入CSV',
    'employees.list': '员工列表',
    'employees.totalCount': '共 {count} 人',
    'employees.searchPlaceholder': '搜索员工...',
    'employees.employeeId': '员工工号',
    'employees.name': '姓名',
    'employees.department': '部门',
    'employees.baseSalary': '基本工资',
    'employees.otRate': '加班费率/小时',
    'employees.loading': '加载中...',
    'employees.noData': '未找到员工',
    'employees.loadError': '无法加载员工数据',
    'employees.importSuccess': '成功导入 {count} 名员工',
    'employees.importError': '导入数据错误',

    // Attendance Page
    'attendance.title': '记录工作时间',
    'attendance.subtitle': '从人脸识别设备导入考勤扫描数据',
    'attendance.import': '导入数据',
    'attendance.uploadDesc': '上传.txt文件或粘贴数据',
    'attendance.uploadFile': '上传文件',
    'attendance.pasteHere': '或在此粘贴数据',
    'attendance.importing': '导入中...',
    'attendance.importData': '导入数据',
    'attendance.dataFormat': '数据格式',
    'attendance.formatDesc': '扫描数据必须遵循此格式',
    'attendance.formatExplain': '格式说明：',
    'attendance.formatMachineId': '机器编号（01、04等）',
    'attendance.formatDate': '日期（DD-MM-YYYY）',
    'attendance.formatTime': '时间（HH:MM:SS）',
    'attendance.formatEmpId': '员工工号（\'20055675）',
    'attendance.formatType': '类型（1=签到，2=签退）',
    'attendance.importSuccess': '导入成功！',
    'attendance.scansImported': '导入了 {count} 次扫描',
    'attendance.recordsCreated': '创建了 {count} 条工作记录',
    'attendance.scansSkipped': '跳过 {count} 条记录（员工不在系统中）',
    'attendance.fileReadSuccess': '文件读取成功',
    'attendance.enterDataError': '请输入扫描数据',

    // Reports Page
    'reports.title': '报告',
    'reports.subtitle': '导出和查看各种系统报告',
    'reports.attendance': '考勤报告',
    'reports.attendanceDesc': '员工签到/签退报告',
    'reports.exportExcel': '导出Excel',
    'reports.otMonthly': '月度加班报告',
    'reports.otMonthlyDesc': '员工加班时间汇总',
    'reports.payroll': '工资报告',
    'reports.payrollDesc': '月度员工工资报告',
    'reports.exportPDF': '导出PDF',
    'reports.payslip': '工资单',
    'reports.payslipDesc': '为员工生成工资单',
    'reports.createPayslip': '创建工资单PDF',
    'reports.leave': '请假报告',
    'reports.leaveDesc': '员工请假汇总',
    'reports.yearlyReport': '年度汇总报告',
    'reports.yearlyReportDesc': '全年工资和加班汇总',
    'reports.viewReport': '查看报告',
    'reports.tips': '提示',
    'reports.tip1': '所有报告均可导出为Excel或PDF文件',
    'reports.tip2': '工资单可生成PDF供员工使用',
    'reports.tip3': '报告可按日期范围和部门筛选',

    // AI Features Page
    'ai.subtitle': '使用AI分析数据、回答问题并自动协助使用工资系统',
    'ai.capabilities': 'AI功能',
    'ai.cap1': '回答有关员工和工资数据的问题',
    'ai.cap2': '分析加班数据和工作绩效',
    'ai.cap3': '提供系统使用指导',
    'ai.cap4': '自动生成报告和摘要',
    'ai.examples': '示例问题',
    'ai.example1': '加班最多的前5名员工是谁？',
    'ai.example2': '生产部门的总工资支出是多少？',
    'ai.example3': '如何导入考勤数据？',
    'ai.example4': '系统中如何计算加班费？',
    'ai.tips': '提示',
    'ai.tip1': '提出具体问题以获得更好的结果',
    'ai.tip2': '可以在同一上下文中提出后续问题',
    'ai.tip3': 'AI会记住之前的对话上下文',
    'ai.comingSoon': '即将推出',

    // Payroll Page (Additional Keys)
    'payroll.pageTitle': '工资管理',
    'payroll.pageSubtitle': '计算和管理员工工资数据',
    'payroll.startDate': '开始日期',
    'payroll.endDate': '结束日期',
    'payroll.autoCalculated': '自动计算',
    'payroll.startDateHint': '仅选择11日或26日',
    'payroll.endDateHint': '从开始日期计算+14天',
    'payroll.baseSalaryCard': '基本工资',
    'payroll.excludingOT': '不包括加班费',
    'payroll.otTotalCard': '总加班费',
    'payroll.totalOTDesc': '总加班费',
    'payroll.grossCard': '总计（税前）',
    'payroll.netCard': '总计（净额）',
    'payroll.netDesc': '扣税+保险后',
    'payroll.employeeList': '员工工资清单',
    'payroll.totalEmployees': '共 {count} 名员工',
    'payroll.searchResults': '搜索结果 {count} 人',
    'payroll.searchByName': '按姓名或工号搜索...',
    'payroll.exportExcel': '导出Excel',
    'payroll.calculateHint': '点击"计算"按钮计算本期工资',
    'payroll.createPeriod': '创建工资周期',
    'payroll.periodSettings': '设置新的工资周期',
    'payroll.periodName': '周期名称',
    'payroll.periodExample': '例如 2025年10月',
    'payroll.paymentDate': '付款日期',
    'payroll.createPeriodBtn': '创建工资周期',
    'payroll.allPeriods': '所有工资周期',
    'payroll.selectPeriodDesc': '选择周期以计算或查看工资详情',
    'payroll.periodRange': '周期：',
    'payroll.paymentOn': '付款日期：',
    'payroll.statusPaid': '已付款',
    'payroll.statusApproved': '已批准',
    'payroll.statusDraft': '草稿',
    'payroll.calculate': '计算',
    'payroll.viewData': '查看数据',
    'payroll.noPeriods': '暂无工资周期',
    'payroll.createFirstPeriod': '创建新的工资周期以开始',
    'payroll.loadingData': '加载中...',
    'payroll.startDateError': '开始日期必须是11日或26日',
    'payroll.selectStartDateError': '请选择有效的开始日期',
    'payroll.createError': '无法创建工资周期',
    'payroll.createSuccess': '工资周期创建成功',
    'payroll.calculateError': '无法计算工资',
    'payroll.calculateSuccess': '成功计算 {count} 条工资记录',
  },
};
